# Generated by Django 3.2.8 on 2022-03-14 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('hospital_phone', models.CharField(max_length=50, unique=True)),
                ('hospital_longtitude', models.FloatField(unique=True)),
                ('hospital_latitude', models.FloatField(unique=True)),
                ('hospital_covid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('room_price', models.IntegerField()),
                ('room_type', models.CharField(max_length=10)),
                ('room_available', models.BooleanField(default=False)),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='FindById',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('date_of_lost', models.DateTimeField(auto_now_add=True)),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='FindByClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_color', models.CharField(max_length=10)),
                ('trouser_color', models.CharField(max_length=10)),
                ('hair_color', models.CharField(max_length=10)),
                ('skin_color', models.CharField(max_length=10)),
                ('height', models.CharField(max_length=5)),
                ('date_of_lost', models.DateTimeField(auto_now_add=True)),
                ('hospitals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='BLoodTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(max_length=5)),
                ('blood_count', models.IntegerField()),
                ('hospitals', models.ManyToManyField(to='api.Hospitals')),
            ],
        ),
    ]
