# Generated by Django 4.0.3 on 2022-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findbyclothes',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='findbyid',
            name='gender',
            field=models.CharField(default='', max_length=5),
        ),
    ]
