# Generated by Django 3.2.8 on 2022-04-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_findbyclothes_gender_findbyid_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('longtitude', models.FloatField(unique=True)),
                ('latitude', models.FloatField(unique=True)),
                ('covid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital')),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='findbyclothes',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='findbyid',
            name='hospitals',
        ),
        migrations.RemoveField(
            model_name='hospitaluser',
            name='hospitals',
        ),
        migrations.DeleteModel(
            name='BLoodTypes',
        ),
        migrations.DeleteModel(
            name='Hospitals',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.AddField(
            model_name='blood',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='findbyclothes',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='findbyid',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hospital'),
        ),
    ]
