# Generated by Django 3.2.8 on 2022-04-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220412_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FindByClothes',
            new_name='FindByClothe',
        ),
    ]
